from django.urls import path

from .views import (
    AdminProductDetailView,
    AdminProductImageDeleteView,
    AdminProductImageUploadView,
    AdminBrandDetailView,
    AdminBrandListCreateView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminColorDetailView,
    AdminColorListCreateView,
    AdminConditionDetailView,
    AdminConditionListCreateView,
    AdminProductListCreateView,
    AdminSizeDetailView,
    AdminSizeListCreateView,
    BrandListView,
    CategoryListView,
    ColorListView,
    ConditionListView,
    FeaturedProductsView,
    NewArrivalsView,
    ProductDetailView,
    ProductListView,
    SizeListView,
)

urlpatterns = [
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/featured/", FeaturedProductsView.as_view(), name="featured-products"),
    path("products/new/", NewArrivalsView.as_view(), name="new-arrivals"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("brands/", BrandListView.as_view(), name="brand-list"),
    path("conditions/", ConditionListView.as_view(), name="condition-list"),
    path("colors/", ColorListView.as_view(), name="color-list"),
    path("sizes/", SizeListView.as_view(), name="size-list"),
    path("admin/products/", AdminProductListCreateView.as_view(), name="admin-product-list"),
    path(
        "admin/products/<int:pk>/",
        AdminProductDetailView.as_view(),
        name="admin-product-detail",
    ),
    path(
        "admin/products/<int:pk>/images/",
        AdminProductImageUploadView.as_view(),
        name="admin-product-images",
    ),
    path(
        "admin/products/<int:pk>/images/<int:image_id>/",
        AdminProductImageDeleteView.as_view(),
        name="admin-product-image-delete",
    ),
    path("admin/configuration/brands/", AdminBrandListCreateView.as_view(), name="admin-brand-list"),
    path("admin/configuration/brands/<int:pk>/", AdminBrandDetailView.as_view(), name="admin-brand-detail"),
    path("admin/configuration/categories/", AdminCategoryListCreateView.as_view(), name="admin-category-list"),
    path("admin/configuration/categories/<int:pk>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("admin/configuration/conditions/", AdminConditionListCreateView.as_view(), name="admin-condition-list"),
    path("admin/configuration/conditions/<int:pk>/", AdminConditionDetailView.as_view(), name="admin-condition-detail"),
    path("admin/configuration/colors/", AdminColorListCreateView.as_view(), name="admin-color-list"),
    path("admin/configuration/colors/<int:pk>/", AdminColorDetailView.as_view(), name="admin-color-detail"),
    path("admin/configuration/sizes/", AdminSizeListCreateView.as_view(), name="admin-size-list"),
    path("admin/configuration/sizes/<int:pk>/", AdminSizeDetailView.as_view(), name="admin-size-detail"),
]
