import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createProductOption, deleteProductOption, getProductOptions, updateProductOption } from '@/services/adminApi';
import { getApiErrorMessage } from '@/lib/api/client';

const optionTypes = [['BRAND', 'Brands'], ['CATEGORY', 'Categories'], ['CONDITION', 'Conditions'], ['COLOR', 'Colors'], ['SIZE', 'Sizes']] as const;
export default function Configuration() {
  const queryClient = useQueryClient(); const [active, setActive] = useState('BRAND'); const [value, setValue] = useState(''); const [editing, setEditing] = useState<{ id?: number; value: string } | null>(null); const [error, setError] = useState('');
  const query = useQuery({ queryKey: ['product-options', active], queryFn: () => getProductOptions(active) });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['product-options'] }); };
  const add = useMutation({ mutationFn: (nextValue?: string) => { const next = (nextValue ?? value).trim(); return createProductOption({ option_type: active, value: next, label: next }); }, onSuccess: () => { setValue(''); setError(''); setEditing(null); refresh(); }, onError: (reason) => setError(getApiErrorMessage(reason)) });
  const remove = useMutation({ mutationFn: deleteProductOption, onSuccess: refresh, onError: (reason) => setError(getApiErrorMessage(reason)) });
  const edit = useMutation({ mutationFn: ({ id, next }: { id: number; next: string }) => updateProductOption(id, { value: next.trim(), label: next.trim() }), onSuccess: () => { setEditing(null); setError(''); refresh(); }, onError: (reason) => setError(getApiErrorMessage(reason)) });
  if (query.isLoading) return <div className="admin-loading">Loading configuration...</div>;
  if (query.isError) return <section><div className="admin-heading"><div><div className="eyebrow">Catalogue controls</div><h1 className="display">Configuration</h1></div></div><div className="error">Could not load configuration: {getApiErrorMessage(query.error)}. Please sign in again if your seller session has expired.</div></section>;
  return <section><div className="admin-heading"><div><div className="eyebrow">Catalogue controls</div><h1 className="display">Configuration</h1></div></div><div className="config-tabs">{optionTypes.map(([type, text]) => <button type="button" className={active === type ? 'active' : ''} key={type} onClick={() => { setActive(type); setError(''); }}>{text}</button>)}</div><div className="admin-section config-panel"><div className="section-head"><h2>{optionTypes.find(([type]) => type === active)?.[1]}</h2><button type="button" className="button" onClick={() => { setValue(''); setError(''); setEditing({ value: '' }); }}>+ Add</button></div>{error && <div className="error">{error}</div>}{(query.data || []).map((option) => <div className="option-row" key={option.id}><span>{option.label}</span><div><button type="button" className="text-button" onClick={() => { setError(''); setEditing({ id: option.id, value: option.label }); }}>Edit</button><button type="button" className="text-button danger" onClick={() => { if (window.confirm(`Delete ${option.label}?`)) remove.mutate(option.id); }}>Delete</button></div></div>)}</div>{editing && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setEditing(null); }}><div className="config-modal" role="dialog" aria-modal="true" aria-labelledby="config-modal-title"><div className="section-head"><h2 id="config-modal-title">{editing.id ? 'Edit' : 'Add'} {optionTypes.find(([type]) => type === active)?.[1].slice(0, -1)}</h2><button type="button" className="icon-button" aria-label="Close" onClick={() => setEditing(null)}>×</button></div><form onSubmit={(event) => { event.preventDefault(); if (!editing.value.trim()) { setError('Enter a value.'); return; } if (editing.id) edit.mutate({ id: editing.id, next: editing.value }); else add.mutate(editing.value); }}><label className="field">Name<input autoFocus value={editing.value} onChange={(event) => setEditing((current) => current ? { ...current, value: event.target.value } : current)} /></label>{error && <div className="error">{error}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={() => setEditing(null)}>Cancel</button><button className="button" disabled={add.isPending || edit.isPending}>{add.isPending || edit.isPending ? 'Saving...' : 'Save'}</button></div></form></div></div>}</section>;
}
