import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createConfiguration, deleteConfiguration, getProductConfiguration, updateConfiguration } from '@/services/adminApi';
import { getApiErrorMessage } from '@/lib/api/client';

const optionTypes = [['BRAND', 'Brands'], ['CATEGORY', 'Categories'], ['CONDITION', 'Conditions'], ['COLOR', 'Colors'], ['SIZE', 'Sizes']] as const;
export default function Configuration() {
  const queryClient = useQueryClient(); const [active, setActive] = useState<(typeof optionTypes)[number][0]>('BRAND'); const [editing, setEditing] = useState<{ id?: number; value: string } | null>(null); const [error, setError] = useState('');
  const query = useQuery({ queryKey: ['product-configuration'], queryFn: getProductConfiguration });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['product-configuration'] }); };
  const items = query.data ? query.data[{ BRAND: 'brands', CATEGORY: 'categories', CONDITION: 'conditions', COLOR: 'colors', SIZE: 'sizes' }[active] as keyof typeof query.data] : [];
  const add = useMutation({ mutationFn: (value: string) => createConfiguration(active, value.trim()), onSuccess: () => { setEditing(null); setError(''); refresh(); }, onError: (reason) => setError(getApiErrorMessage(reason)) });
  const edit = useMutation({ mutationFn: ({ id, value }: { id: number; value: string }) => updateConfiguration(active, id, value.trim()), onSuccess: () => { setEditing(null); setError(''); refresh(); }, onError: (reason) => setError(getApiErrorMessage(reason)) });
  const remove = useMutation({ mutationFn: (id: number) => deleteConfiguration(active, id), onSuccess: refresh, onError: (reason) => setError(getApiErrorMessage(reason)) });
  if (query.isLoading) return <div className="admin-loading">Loading configuration...</div>;
  if (query.isError || !query.data) return <section><div className="admin-heading"><div><div className="eyebrow">Catalogue controls</div><h1 className="display">Configuration</h1></div></div><div className="error">Could not load configuration: {getApiErrorMessage(query.error)}. Please sign in again if your seller session has expired.</div></section>;
  return <section><div className="admin-heading"><div><div className="eyebrow">Catalogue controls</div><h1 className="display">Configuration</h1></div></div><div className="config-tabs">{optionTypes.map(([type, text]) => <button type="button" className={active === type ? 'active' : ''} key={type} onClick={() => { setActive(type); setError(''); }}>{text}</button>)}</div><div className="admin-section config-panel"><div className="section-head"><h2>{optionTypes.find(([type]) => type === active)?.[1]}</h2><button type="button" className="button" onClick={() => { setError(''); setEditing({ value: '' }); }}>+ Add</button></div>{error && <div className="error">{error}</div>}{items.map((option) => { const displayValue = option.name || option.value || ''; return <div className="option-row" key={option.id}><span>{displayValue}</span><div><button type="button" className="text-button" onClick={() => setEditing({ id: option.id, value: displayValue })}>Edit</button><button type="button" className="text-button danger" onClick={() => { if (window.confirm(`Delete ${displayValue}?`)) remove.mutate(option.id); }}>Delete</button></div></div>; })}</div>{editing && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setEditing(null); }}><div className="config-modal" role="dialog" aria-modal="true" aria-labelledby="config-modal-title"><div className="section-head"><h2 id="config-modal-title">{editing.id ? 'Edit' : 'Add'} {optionTypes.find(([type]) => type === active)?.[1].slice(0, -1)}</h2><button type="button" className="icon-button" aria-label="Close" onClick={() => setEditing(null)}>×</button></div><form onSubmit={(event) => { event.preventDefault(); if (!editing.value.trim()) { setError('Enter a value.'); return; } if (editing.id) edit.mutate({ id: editing.id, value: editing.value }); else add.mutate(editing.value); }}><label className="field">Name<input autoFocus value={editing.value} onChange={(event) => setEditing((current) => current ? { ...current, value: event.target.value } : current)} /></label>{error && <div className="error">{error}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={() => setEditing(null)}>Cancel</button><button className="button" disabled={add.isPending || edit.isPending}>Save</button></div></form></div></div>}</section>;
}
