import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createProduct, deleteProductImage, getProductOptions, type ProductInput, updateProduct, uploadProductImages } from '@/services/adminApi';
import { getApiErrorMessage } from '@/lib/api/client';
import type { Product } from '@/types';

const blankProduct: ProductInput = { name: '', description: '', brand: '', category: '', price: '', condition: '', color: '', status: 'DRAFT', is_featured: false, variants: [] };
const statuses = ['DRAFT', 'PUBLISHED', 'HIDDEN'];
const label = (value: string) => value.replace(/_/g, ' ').toLowerCase().replace(/(^|\s)\S/g, (char) => char.toUpperCase());

export default function ProductForm({ product, onDone }: { product?: Product; onDone: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState<ProductInput>(product ? { name: product.name, description: product.description || '', brand: product.brand, category: product.category, price: product.price, condition: product.condition || '', color: product.color, status: product.status, is_featured: product.is_featured, variants: product.variants?.map(({ size, stock_quantity, sku, is_active }) => ({ size, stock_quantity, sku, is_active })) || [] } : blankProduct);
  const [files, setFiles] = useState<File[]>([]); const [error, setError] = useState('');
  const options = useQuery({ queryKey: ['product-options'], queryFn: () => getProductOptions() });
  const byType = (type: string) => (options.data || []).filter((option) => option.option_type === type);
  const save = useMutation({ mutationFn: async () => { const saved = product ? await updateProduct(product.id, form) : await createProduct(form); return files.length ? uploadProductImages(saved.id, files) : saved; }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['admin-products'] }); onDone(); }, onError: (reason) => setError(getApiErrorMessage(reason)) });
  const update = (key: keyof ProductInput, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const updateVariant = (index: number, key: 'stock_quantity' | 'sku', value: string) => setForm((current) => ({ ...current, variants: current.variants.map((variant, row) => row === index ? { ...variant, [key]: key === 'stock_quantity' ? Number(value) : value } : variant) }));
  const addVariant = (size: string) => { if (!size || form.variants.some((variant) => variant.size === size)) return; setForm((current) => ({ ...current, variants: [...current.variants, { size, stock_quantity: 0, sku: '', is_active: true }] })); };
  const totalStock = form.variants.reduce((sum, variant) => sum + (Number(variant.stock_quantity) || 0), 0);
  const selectOptions = (type: string, current: string) => <><option value="">Select {type.toLowerCase()}</option>{byType(type).map((option) => <option key={option.id} value={option.value}>{option.label}</option>)}{current && !byType(type).some((option) => option.value === current) && <option value={current}>{current}</option>}</>;
  const chooseFiles = (selected: FileList | null) => { const selectedFiles = Array.from(selected || []); const valid = selectedFiles.filter((file) => file.type.startsWith('image/') && file.size <= 5 * 1024 * 1024); if (valid.length !== selectedFiles.length) setError('Images must be supported image files smaller than 5 MB.'); setFiles((current) => [...current, ...valid]); };
  const submit = (event: FormEvent) => { event.preventDefault(); setError(''); if (!form.name || !form.brand || !form.category || !form.condition || !form.color || Number(form.price) <= 0) return setError('Complete all required fields and enter a price greater than zero.'); if (form.variants.some((variant) => !variant.size || !variant.sku)) return setError('Each size row needs a size and SKU.'); save.mutate(); };
  if (options.isLoading) return <div className="admin-loading">Loading product configuration...</div>;
  if (options.isError) return <div className="error">Could not load product configuration: {getApiErrorMessage(options.error)}. Please refresh or sign in again.</div>;
  if (!options.data?.length) return <div className="error">No product configuration options are available. Add brands, categories, conditions, colors, and sizes from Configuration first.</div>;
  return <form className="admin-form product-form-wide" onSubmit={submit}>
    <div className="form-section"><div className="section-kicker">Basic information</div><div className="form-grid"><label className="field">Product name<input value={form.name} onChange={(event) => update('name', event.target.value)} required /></label><label className="field">Brand<select value={form.brand} onChange={(event) => update('brand', event.target.value)} required>{selectOptions('brand', form.brand)}</select></label><label className="field">Category<select value={form.category} onChange={(event) => update('category', event.target.value)} required>{selectOptions('category', form.category)}</select></label><label className="field">Price<input type="number" min="0.01" step="0.01" value={form.price} onChange={(event) => update('price', event.target.value)} required /></label><label className="field">Condition<select value={form.condition} onChange={(event) => update('condition', event.target.value)} required>{selectOptions('condition', form.condition)}</select></label><label className="field">Color<select value={form.color} onChange={(event) => update('color', event.target.value)} required>{selectOptions('color', form.color)}</select></label></div></div>
    <div className="form-section"><div className="section-kicker">Description</div><label className="field">Description<textarea rows={4} value={form.description} onChange={(event) => update('description', event.target.value)} /></label></div>
    <div className="form-section"><div className="section-kicker">Product images</div><label className="upload-zone">+ Upload images<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={(event) => chooseFiles(event.target.files)} /><small>PNG, JPG, or WebP up to 5 MB each</small></label>{files.length > 0 && <div className="image-preview-grid">{files.map((file, index) => <div className="image-preview" key={`${file.name}-${index}`}><img src={URL.createObjectURL(file)} alt="" /><button type="button" className="icon-button" onClick={() => setFiles((current) => current.filter((_, row) => row !== index))}>×</button>{index === 0 && <small>Primary image</small>}</div>)}</div>}{product?.images?.length ? <div className="image-preview-grid">{product.images.map((image) => <div className="image-preview" key={image.id}><img src={image.image_url || ''} alt={image.alt_text} /><button type="button" className="icon-button" onClick={async () => { await deleteProductImage(product.id, image.id); void queryClient.invalidateQueries({ queryKey: ['admin-products'] }); }}>×</button></div>)}</div> : null}</div>
    <div className="form-section"><div className="section-kicker">Sizes & stock</div>{form.variants.map((variant, index) => <div className="variant-row" key={`${variant.size}-${index}`}><input aria-label="Size" value={variant.size} readOnly /><input aria-label="Quantity" type="number" min="0" value={variant.stock_quantity} onChange={(event) => updateVariant(index, 'stock_quantity', event.target.value)} /><input aria-label="SKU" value={variant.sku} placeholder="SKU" onChange={(event) => updateVariant(index, 'sku', event.target.value)} /><button type="button" className="icon-button" onClick={() => setForm((current) => ({ ...current, variants: current.variants.filter((_, row) => row !== index) }))}>×</button></div>)}<div className="variant-add"><select value="" onChange={(event) => addVariant(event.target.value)}><option value="">Select size to add</option>{byType('SIZE').filter((option) => !form.variants.some((variant) => variant.size === option.value)).map((option) => <option key={option.id} value={option.value}>{option.label}</option>)}</select><strong>Total stock: {totalStock} units</strong></div></div>
    <div className="form-section"><div className="section-kicker">Publishing</div><div className="form-grid"><label className="field">Visibility<select value={form.status} onChange={(event) => update('status', event.target.value)}>{statuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label><label className="check"><input type="checkbox" checked={form.is_featured} onChange={(event) => update('is_featured', event.target.checked)} /> Feature this product</label></div></div>{error && <div className="error">{error}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={onDone}>Cancel</button><button className="button" disabled={save.isPending}>{save.isPending ? 'Saving...' : product ? 'Save product' : 'Add product'}</button></div>
  </form>;
}
