# Generated by Django 5.1.15 on 2026-09-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_align_product_index_state"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("sku",),
                name="unique_non_empty_sku",
            ),
        ),
    ]
